// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Agent is one registered ACP agent.
 * 
 * Env is injected per process at spawn time, which is how several agents (two
 * Codex accounts, say) coexist on one machine: give each its own
 * CODEX_HOME/OPENAI_API_KEY or CLAUDE_CONFIG_DIR/ANTHROPIC_API_KEY.
 */
export class Agent {
    /**
     * registry key; matches a card's assignee
     */
    "name": string;
    "kind": string;

    /**
     * BinPath overrides adapter discovery. A path typed here is an instruction,
     * not a hint: if it does not work the agent fails to start rather than
     * quietly running something else.
     */
    "binPath"?: string;
    "model"?: string;

    /**
     * Prompt is prepended to every task this agent is given — who it is, before
     * what the stage and the card ask of it.
     */
    "prompt"?: string;
    "env"?: { [_ in string]?: string };
    "args"?: string[];

    /**
     * Command is the whole launch argv, required for KindACP. It replaces the
     * adapter binary we would have looked up, so a wrapper can get in front of
     * it. With it set nothing of ours is appended, so the flags the kind would
     * have carried have to be spelled out.
     */
    "command"?: string[];

    /**
     * AutoAllowTools overrides the machine-wide policy for this agent, so a
     * trusted one can be let loose and a new one kept on a short leash without
     * changing anything for the rest. Entries take the form "Read" or
     * "Bash(git *)".
     */
    "autoAllowTools"?: string[];

    /** Creates a new Agent instance. */
    constructor($$source: Partial<Agent> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Agent instance from a string or object.
     */
    static createFrom($$source: any = {}): Agent {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField5_0($$parsedSource["env"]);
        }
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField6_0($$parsedSource["args"]);
        }
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField7_0($$parsedSource["command"]);
        }
        if ("autoAllowTools" in $$parsedSource) {
            $$parsedSource["autoAllowTools"] = $$createField8_0($$parsedSource["autoAllowTools"]);
        }
        return new Agent($$parsedSource as Partial<Agent>);
    }
}

/**
 * Card is one unit of work: something a source brought, or something a person
 * typed.
 */
export class Card {
    "id": string;

    /**
     * Source is what brought the card, and it is what the inbox groups by.
     * Empty means a person made it here.
     */
    "source"?: string;

    /**
     * ExternalID and ItemVersion are which item of the source this card was
     * made from, and the state of that item when it was. Together they are what
     * stops the same letter becoming a second card.
     */
    "externalId"?: string;
    "itemVersion"?: string;
    "title": string;
    "body"?: string;

    /**
     * URL is the way back to the original.
     */
    "url"?: string;
    "state": CardState;

    /**
     * Assignee is who the card is for. An agent name means "let this agent
     * work it"; anything else means a person took it, and then no agent starts
     * (see PickAgent).
     */
    "assignee"?: string;

    /**
     * Props are the card's own named values. A flow condition asks about these,
     * and a person answers a waiting stage by setting one.
     */
    "props"?: { [_ in string]?: string };
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Card instance. */
    constructor($$source: Partial<Card> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = CardState.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Card instance from a string or object.
     */
    static createFrom($$source: any = {}): Card {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField9_0($$parsedSource["props"]);
        }
        return new Card($$parsedSource as Partial<Card>);
    }
}

/**
 * CardState is where a card is in its life. Exactly four, and a card in state
 * StateFlow always stands on some stage — "on a flow but nowhere" is an
 * invariant, not a convention (docs/system.md §3).
 */
export enum CardState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateInbox = "inbox",
    StateFlow = "flow",
    StateDone = "done",
    StateDropped = "dropped",
};

/**
 * Comment is one line of a card's history: what a session said, what a flow
 * decided, what a person answered.
 */
export class Comment {
    "id": number;
    "cardId": string;

    /**
     * Author is who spoke: an agent's name, a source's name, or empty for the
     * application itself.
     */
    "author"?: string;
    "text": string;
    "createdAt": string;

    /** Creates a new Comment instance. */
    constructor($$source: Partial<Comment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cardId" in $$source)) {
            this["cardId"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Comment instance from a string or object.
     */
    static createFrom($$source: any = {}): Comment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Comment($$parsedSource as Partial<Comment>);
    }
}

/**
 * Cond is what a conditional transition asks about, in exactly one of two
 * forms. Both are questions about the card, not scripts.
 */
export class Cond {
    /**
     * Property/Value: the card carries this property with this value.
     */
    "property"?: string;
    "value"?: string;

    /**
     * CommentContains: the agent's closing words contain this text — how a
     * stage lets the agent itself route the card («ГОТОВО К ДЕПЛОЮ»).
     */
    "commentContains"?: string;

    /** Creates a new Cond instance. */
    constructor($$source: Partial<Cond> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cond instance from a string or object.
     */
    static createFrom($$source: any = {}): Cond {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cond($$parsedSource as Partial<Cond>);
    }
}

/**
 * Edge is one transition.
 */
export class Edge {
    "id"?: string;
    "from": string;
    "to": string;
    "on": string;

    /**
     * If makes the transition conditional. Several conditional edges may share
     * one (From, On) — the first whose condition holds wins, and an edge with
     * no condition is the fallback. For TriggerCardChanged the condition is not
     * a guard but the event itself: which value firing it means.
     */
    "if"?: Cond | null;

    /** Creates a new Edge instance. */
    constructor($$source: Partial<Edge> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("on" in $$source)) {
            this["on"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Edge instance from a string or object.
     */
    static createFrom($$source: any = {}): Edge {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("if" in $$parsedSource) {
            $$parsedSource["if"] = $$createField4_0($$parsedSource["if"]);
        }
        return new Edge($$parsedSource as Partial<Edge>);
    }
}

/**
 * Flow is one named route.
 */
export class Flow {
    "id": string;
    "name": string;
    "description"?: string;

    /**
     * EntryStage is where a card taken into work starts. It is stated rather
     * than inferred: a graph with a loop has no stage without incoming edges,
     * so guessing the start breaks a flow at its first backward transition.
     */
    "entryStage": string;
    "stages": Stage[];
    "edges": Edge[];

    /** Creates a new Flow instance. */
    constructor($$source: Partial<Flow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("entryStage" in $$source)) {
            this["entryStage"] = "";
        }
        if (!("stages" in $$source)) {
            this["stages"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Flow instance from a string or object.
     */
    static createFrom($$source: any = {}): Flow {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField4_0($$parsedSource["stages"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField5_0($$parsedSource["edges"]);
        }
        return new Flow($$parsedSource as Partial<Flow>);
    }
}

/**
 * FlowEvent is one recorded transition — the answer to "why is this card here".
 */
export class FlowEvent {
    "id": number;
    "cardId": string;
    "flowId": string;
    "fromStage"?: string;
    "toStage": string;
    "on"?: string;
    "detail"?: string;
    "createdAt": string;

    /** Creates a new FlowEvent instance. */
    constructor($$source: Partial<FlowEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cardId" in $$source)) {
            this["cardId"] = "";
        }
        if (!("flowId" in $$source)) {
            this["flowId"] = "";
        }
        if (!("toStage" in $$source)) {
            this["toStage"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlowEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): FlowEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlowEvent($$parsedSource as Partial<FlowEvent>);
    }
}

/**
 * InboxGroup is the inbox as it is read: one source and its cards. Cards
 * grouped by what brought them is the whole of the inbox screen.
 */
export class InboxGroup {
    "source": string;
    "cards": Card[];

    /** Creates a new InboxGroup instance. */
    constructor($$source: Partial<InboxGroup> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("cards" in $$source)) {
            this["cards"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InboxGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): InboxGroup {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cards" in $$parsedSource) {
            $$parsedSource["cards"] = $$createField1_0($$parsedSource["cards"]);
        }
        return new InboxGroup($$parsedSource as Partial<InboxGroup>);
    }
}

/**
 * Match is what a rule looks at. An empty Match matches everything, which is
 * how a catch-all rule is written; every field given must match, so a rule with
 * two fields is an "and".
 */
export class Match {
    /**
     * regexp
     */
    "title"?: string;

    /**
     * regexp
     */
    "body"?: string;

    /**
     * any one of them
     */
    "labels"?: string[];

    /**
     * property → regexp
     */
    "props"?: { [_ in string]?: string };

    /** Creates a new Match instance. */
    constructor($$source: Partial<Match> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Match instance from a string or object.
     */
    static createFrom($$source: any = {}): Match {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField3_0($$parsedSource["props"]);
        }
        return new Match($$parsedSource as Partial<Match>);
    }
}

/**
 * Rule is what to do with an item. Rules are tried in order and the first match
 * wins, so the catch-all goes last.
 */
export class Rule {
    "name"?: string;
    "when": Match;
    "then": string;

    /**
     * Props are card properties, as Go templates over the item:
     * {"Ссылка": "{{.URL}}"}.
     */
    "props"?: { [_ in string]?: string };

    /**
     * SuggestFlow prefills the flow in the «В работу» dialog. It is a
     * suggestion and nothing more: taking a card into work is a person's
     * decision (docs/system.md §3), so a rule may say which flow it expects
     * but may not start one.
     */
    "suggestFlow"?: string;

    /**
     * Assignee prefills who the card is for, the same way and for the same
     * reason.
     */
    "assignee"?: string;

    /** Creates a new Rule instance. */
    constructor($$source: Partial<Rule> = {}) {
        if (!("when" in $$source)) {
            this["when"] = (new Match());
        }
        if (!("then" in $$source)) {
            this["then"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rule instance from a string or object.
     */
    static createFrom($$source: any = {}): Rule {
        const $$createField1_0 = $$createType10;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("when" in $$parsedSource) {
            $$parsedSource["when"] = $$createField1_0($$parsedSource["when"]);
        }
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField3_0($$parsedSource["props"]);
        }
        return new Rule($$parsedSource as Partial<Rule>);
    }
}

/**
 * Source is one registered source.
 */
export class Source {
    "name": string;
    "plugin"?: string;
    "enabled": boolean;

    /**
     * Noisy inverts the default for what matched no rule: a stream of
     * notifications is mostly noise, so there a rule is a subscription and
     * everything else is dropped. For an ordinary source the opposite holds —
     * silently losing an item is what makes an integration impossible to debug
     * — so it goes to the inbox instead.
     */
    "noisy"?: boolean;

    /**
     * Update says what a changed item does to the card it already has.
     * comment (default) | ignore
     */
    "update"?: string;
    "config"?: { [_ in string]?: string };
    "intervalSeconds"?: number;
    "rules"?: Rule[];

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField5_0($$parsedSource["config"]);
        }
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField7_0($$parsedSource["rules"]);
        }
        return new Source($$parsedSource as Partial<Source>);
    }
}

/**
 * Stage is one node: the place a card stands, and the work done there.
 * 
 * In XCIII a stage referenced a board column and the column carried the
 * behaviour. There is no board here, so a stage is the only place a card can
 * stand and there is nothing left to split off — see docs/system.md §1.
 */
export class Stage {
    /**
     * ID is unique across every flow, not merely within one: a card records
     * where it stands by stage id, and "which flow is this stage in" has to
     * have one answer. The editor generates them, so this costs nothing; a
     * hand-written flow that reuses an id is refused by name.
     */
    "id": string;
    "name": string;
    "action": string;

    /**
     * Prompt is what the agent is told about this step, on top of its own
     * prompt and the card's task.
     */
    "prompt"?: string;

    /**
     * Crew is who may work this stage. Not an assignment but a list of who is
     * allowed at all: the card chooses among them (see PickAgent).
     */
    "crew"?: string[];

    /**
     * MaxRunning bounds how many cards this stage works at once. Zero means no
     * limit of its own; the machine-wide limit still applies.
     */
    "maxRunning"?: number;

    /**
     * Final says a card reaching this stage is done. It runs nothing and leads
     * nowhere.
     */
    "final"?: boolean;

    /**
     * X and Y are where the editor left the stage on its canvas. Absent means
     * "lay it out for me" — a flow written by hand never has to place anything.
     */
    "x"?: number;
    "y"?: number;

    /** Creates a new Stage instance. */
    constructor($$source: Partial<Stage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stage instance from a string or object.
     */
    static createFrom($$source: any = {}): Stage {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("crew" in $$parsedSource) {
            $$parsedSource["crew"] = $$createField4_0($$parsedSource["crew"]);
        }
        return new Stage($$parsedSource as Partial<Stage>);
    }
}

/**
 * Trigger describes one edge trigger. The list doubles as the editor's
 * dropdown, so the UI can never offer a trigger the engine does not implement.
 */
export class Trigger {
    "kind": string;
    "source": string;
    "label": string;

    /** Creates a new Trigger instance. */
    constructor($$source: Partial<Trigger> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Trigger instance from a string or object.
     */
    static createFrom($$source: any = {}): Trigger {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Trigger($$parsedSource as Partial<Trigger>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Cond.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = Stage.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Edge.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Card.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Match.createFrom;
const $$createType11 = Rule.createFrom;
const $$createType12 = $Create.Array($$createType11);
