// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as msg$0 from "../msg/models.js";

/**
 * Agent is one registered ACP agent.
 * 
 * Env is injected per process at spawn time, which is how several agents (two
 * Codex accounts, say) coexist on one machine: give each its own
 * CODEX_HOME/OPENAI_API_KEY or CLAUDE_CONFIG_DIR/ANTHROPIC_API_KEY.
 */
export interface Agent {
    /**
     * registry key; matches a card's assignee
     */
    "name": string;
    "kind": string;

    /**
     * BinPath overrides adapter discovery. A path typed here is an instruction,
     * not a hint: if it does not work the agent fails to start rather than
     * quietly running something else.
     */
    "binPath"?: string;
    "model"?: string;

    /**
     * Prompt is prepended to every task this agent is given — who it is, before
     * what the stage and the card ask of it.
     */
    "prompt"?: string;
    "env"?: { [_ in string]?: string } | null;
    "args"?: string[] | null;

    /**
     * Command is the whole launch argv, required for KindACP. It replaces the
     * adapter binary we would have looked up, so a wrapper can get in front of
     * it. With it set nothing of ours is appended, so the flags the kind would
     * have carried have to be spelled out.
     */
    "command"?: string[] | null;

    /**
     * AutoAllowTools overrides the machine-wide policy for this agent, so a
     * trusted one can be let loose and a new one kept on a short leash without
     * changing anything for the rest. Entries take the form "Read" or
     * "Bash(git *)".
     */
    "autoAllowTools"?: string[] | null;
}

/**
 * Card is one unit of work: something a source brought, or something a person
 * typed.
 */
export interface Card {
    "id": string;

    /**
     * Source is what brought the card, and it is what the inbox groups by.
     * Empty means a person made it here.
     */
    "source"?: string;

    /**
     * ExternalID and ItemVersion are which item of the source this card was
     * made from, and the state of that item when it was. Together they are what
     * stops the same letter becoming a second card.
     */
    "externalId"?: string;
    "itemVersion"?: string;
    "title": string;
    "body"?: string;

    /**
     * URL is the way back to the original.
     */
    "url"?: string;
    "state": CardState;

    /**
     * Assignee is who the card is for. An agent name means "let this agent
     * work it"; anything else means a person took it, and then no agent starts
     * (see PickAgent).
     */
    "assignee"?: string;

    /**
     * Project is where the work happens: the id of a registry entry, so the
     * project can be renamed without the card noticing. Empty is a real answer —
     * a task that starts from a blank page gets a folder of its own.
     */
    "project"?: string;

    /**
     * WorkMode is how the card works in its project when that is a repository
     * (workmode.go). A person's answer, like the project itself.
     */
    "workMode"?: string;

    /**
     * Branch, Base and Worktree are what that answer came to, written the first
     * time the card's work needed a folder: the card's branch, what it was cut
     * from, and — for a separate working tree — where that tree is. Empty until
     * then. Once written they are the fact, and the mode no longer changes:
     * the work is on that branch.
     */
    "branch"?: string;
    "base"?: string;
    "worktree"?: string;

    /**
     * Session is a conversation the card was started from: one somebody had
     * with the assignee's own CLI before the card existed. The card's first
     * terminal stage for that agent picks it up rather than starting fresh,
     * which is the whole difference between «continue this» and «do this».
     */
    "session"?: string;

    /**
     * Props are the card's own named values. A flow condition asks about these,
     * and a person answers a waiting stage by setting one.
     */
    "props"?: { [_ in string]?: string } | null;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * CardState is where a card is in its life. Exactly four, and a card in state
 * StateFlow always stands on some stage — "on a flow but nowhere" is an
 * invariant, not a convention (docs/system.md §3).
 */
export enum CardState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateInbox = "inbox",
    StateFlow = "flow",
    StateDone = "done",
    StateDropped = "dropped",
};

/**
 * Cond is what a conditional transition asks about, in exactly one of two
 * forms. Both are questions about the card, not scripts.
 */
export interface Cond {
    /**
     * Property/Value: the card carries this property with this value.
     */
    "property"?: string;
    "value"?: string;

    /**
     * CommentContains: the agent's closing words contain this text — how a
     * stage lets the agent itself route the card («READY TO DEPLOY»).
     */
    "commentContains"?: string;
}

/**
 * Edge is one transition.
 */
export interface Edge {
    "id"?: string;
    "from": string;
    "to": string;
    "on": string;

    /**
     * If makes the transition conditional. Several conditional edges may share
     * one (From, On) — the first whose condition holds wins, and an edge with
     * no condition is the fallback. For TriggerCardChanged the condition is not
     * a guard but the event itself: which value firing it means.
     */
    "if"?: Cond | null;
}

/**
 * EntryKind is what a journal entry is. A closed set: the ribbon picks what it
 * shows by it, and a kind it does not know is a kind it silently drops. Empty
 * on the entries written before kinds were recorded: those are journal only.
 */
export enum EntryKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * EntryMove: the card entered a stage, finished its flow, left it, or an
     * agent opened its terminal. Journal only — on the ribbon these are the
     * segments themselves.
     */
    EntryMove = "move",

    /**
     * EntryProblem: why the card stands, or why a step broke. A plaque on its
     * segment.
     */
    EntryProblem = "problem",

    /**
     * EntryReport: what an agent said its step came to. Under its screen.
     */
    EntryReport = "report",

    /**
     * EntryAsk: an agent's question and the answer to it. Journal only — on
     * the ribbon they are part of the agent's stream.
     */
    EntryAsk = "ask",

    /**
     * EntryProps: a stage put values on the card. Journal only — the values
     * are on the card.
     */
    EntryProps = "props",

    /**
     * EntrySource: the source the card came from changed its item.
     */
    EntrySource = "source",

    /**
     * EntryReview: a person sent the work back and said what is wrong with
     * it. A plaque on the segment it was said on, because it is the reason the
     * next one exists.
     */
    EntryReview = "review",
};

/**
 * Flow is one named route.
 */
export interface Flow {
    "id": string;
    "name": string;
    "description"?: string;

    /**
     * EntryStage is where a card taken into work starts. It is stated rather
     * than inferred: a graph with a loop has no stage without incoming edges,
     * so guessing the start breaks a flow at its first backward transition.
     */
    "entryStage": string;
    "stages": Stage[] | null;
    "edges": Edge[] | null;
}

/**
 * FlowEvent is one recorded transition — the answer to "why is this card here".
 */
export interface FlowEvent {
    "id": number;
    "cardId": string;
    "flowId": string;
    "fromStage"?: string;
    "toStage": string;
    "on"?: string;
    "detail"?: msg$0.Msg | null;
    "createdAt": string;
}

/**
 * InboxGroup is the inbox as it is read: one source and its cards. Cards
 * grouped by what brought them is the whole of the inbox screen.
 */
export interface InboxGroup {
    "source": string;

    /**
     * Plugin is what kind of source it is, for the screen to word.
     */
    "plugin"?: string;
    "cards": Card[] | null;
}

/**
 * JournalEntry is one line of a card's journal: who did what to it, and when.
 * The journal is an audit — written always, read when somebody goes looking —
 * and what a person watches the work by is the ribbon (docs/system.md §12).
 * The table is still card_comment: a migration step is never edited.
 */
export interface JournalEntry {
    "id": number;
    "cardId": string;
    "kind": EntryKind;

    /**
     * Author is who spoke: an agent's name, a source's name, or empty for the
     * application itself.
     */
    "author"?: string;

    /**
     * Msg is what the application itself says, for the UI to word. Text is
     * words somebody else wrote — an agent's report, a person's answer — and
     * the entries from before the application spoke in codes.
     */
    "msg"?: msg$0.Msg | null;
    "text"?: string;

    /**
     * SessionID is the agent run the entry was written for, when there was
     * one. It ties a step's report and its failure to their own screen: a
     * report is written the moment before the card moves on, in the same
     * millisecond as the next transition, and by time it would land on the
     * wrong segment.
     */
    "sessionId"?: string;

    /**
     * EventID is the transition the card stood in when the entry was written —
     * the segment it belongs to, for the entries no run is behind. Zero on the
     * entries written before it was recorded.
     */
    "eventId"?: number;
    "createdAt": string;
}

/**
 * Mark is a way a person can move a card from where it stands: the value they
 * would put in the outcome field, and the stage that value leads to.
 * 
 * It exists because a stage where nobody works and nothing runs waits for a
 * person to say how it went — and saying so was finding a field on the card and
 * picking a value out of it, three clicks from the card's face. There are two
 * answers and the flow already knows where each of them leads, so the card can
 * offer them as what they are: forward, and back.
 */
export interface Mark {
    "value": string;
    "stage": string;

    /**
     * Forward is the answer that carries the work on, as against the one that
     * sends it back. It decides which way the arrow points and nothing else.
     */
    "forward": boolean;
}

/**
 * Match is what a rule looks at. An empty Match matches everything, which is
 * how a catch-all rule is written; every field given must match, so a rule with
 * two fields is an "and".
 */
export interface Match {
    /**
     * regexp
     */
    "title"?: string;

    /**
     * regexp
     */
    "body"?: string;

    /**
     * any one of them
     */
    "labels"?: string[] | null;

    /**
     * property → regexp
     */
    "props"?: { [_ in string]?: string } | null;
}

/**
 * Project is one place work is done.
 */
export interface Project {
    /**
     * ID is what a card points at, and the one field that never changes: a
     * project can be renamed without dragging anything behind it, because a
     * name is a label and this is the reference.
     */
    "id": string;
    "name": string;
    "kind": string;

    /**
     * Path is the folder, absolute. For a kind that is not a folder this is
     * where it lands on this machine once it is fetched.
     */
    "path": string;

    /**
     * Repo says the folder is a git repository, which is what offers a card
     * the choice of a branch of its own. Not stored: asked of the folder when
     * the registry is read, since a folder can become one at any time.
     */
    "repo"?: boolean;

    /**
     * Remote, Server and Provider are the project's hosting, as a person set
     * it up: which of the repository's remotes is the one on the hosting —
     * «origin», or «upstream» where origin is a fork — the server's address as
     * its web interface opens it, and which hosting it is. Chosen, not guessed:
     * a server's name says nothing reliable about what it runs, and ssh and
     * the web interface are not always on one host. Empty until connected.
     * 
     * The remote is kept by name and its address asked of git when needed, so
     * a remote pointed somewhere else in git is followed rather than
     * remembered wrong.
     */
    "remote"?: string;
    "server"?: string;
    "provider"?: string;

    /**
     * Repository is the project's path on the server, «group/repo», read off
     * the remote's address. Not stored: it is the remote, read another way.
     */
    "repository"?: string;

    /**
     * Account is who the application is on the hosting, when a token is kept
     * for its server. Not stored with the project: the token belongs to the
     * server, and every project on it shares the answer.
     */
    "account"?: string;

    /**
     * ReviewInbox says the merge requests waiting on this account's review
     * come into the inbox. Read off the source registry, where it lives.
     */
    "reviewInbox"?: boolean;
}

/**
 * PropertyWrite is one property a stage puts on the card: its name, and whether
 * the stage may finish without it. The value is not here — the agent supplies it
 * when it ends.
 */
export interface PropertyWrite {
    "property": string;
    "required"?: boolean;
}

/**
 * Rule is what to do with an item. Rules are tried in order and the first match
 * wins, so the catch-all goes last.
 */
export interface Rule {
    "name"?: string;
    "when": Match;
    "then": string;

    /**
     * Props are card properties, as Go templates over the item:
     * {"Link": "{{.URL}}"}.
     */
    "props"?: { [_ in string]?: string } | null;

    /**
     * SuggestFlow prefills the flow in the «Take into work» dialog. It is a
     * suggestion and nothing more: taking a card into work is a person's
     * decision (docs/system.md §3), so a rule may say which flow it expects
     * but may not start one.
     */
    "suggestFlow"?: string;

    /**
     * Assignee prefills who the card is for, the same way and for the same
     * reason.
     */
    "assignee"?: string;
}

/**
 * Screen is one window inside a ribbon segment: what kind it is, what to call
 * it, and what it points at — a file path, a command line or an address,
 * depending on the kind.
 * 
 * Ref may name card properties as «{Preview}». That is the same currency as a
 * stage's declared inputs (docs/system.md §4.3): the stage that writes the
 * preview address is the stage the browser screen below it opens.
 */
export interface Screen {
    "kind": string;
    "title"?: string;
    "ref"?: string;
}

/**
 * Source is one registered source.
 */
export interface Source {
    "name": string;
    "plugin"?: string;
    "enabled": boolean;

    /**
     * Noisy inverts the default for what matched no rule: a stream of
     * notifications is mostly noise, so there a rule is a subscription and
     * everything else is dropped. For an ordinary source the opposite holds —
     * silently losing an item is what makes an integration impossible to debug
     * — so it goes to the inbox instead.
     */
    "noisy"?: boolean;

    /**
     * Update says what a changed item does to the card it already has.
     * update (default) | ignore
     */
    "update"?: string;
    "config"?: { [_ in string]?: string } | null;
    "intervalSeconds"?: number;
    "rules"?: Rule[] | null;
}

/**
 * Stage is one node: the place a card stands, and the work done there.
 * 
 * In XCIII a stage referenced a board column and the column carried the
 * behaviour. There is no board here, so a stage is the only place a card can
 * stand and there is nothing left to split off — see docs/system.md §1.
 */
export interface Stage {
    /**
     * ID is unique across every flow, not merely within one: a card records
     * where it stands by stage id, and "which flow is this stage in" has to
     * have one answer. The editor generates them, so this costs nothing; a
     * hand-written flow that reuses an id is refused by name.
     */
    "id": string;
    "name": string;
    "action": string;

    /**
     * Work says where an agent stage runs: in the card's terminal, where a
     * person is sitting, or as an ACP session nobody watches (§4.1.1). Empty
     * means WorkTerminal — a stage that did not say is a stage somebody meant
     * to watch, and the mode that shows more is the safe default for a flow
     * written before the field existed.
     * 
     * Meaningless without ActionAgent, and refused there: a waiting stage runs
     * nothing, and nothing has no place to run in.
     */
    "work"?: string;

    /**
     * Prompt is what the agent is told about this step, on top of its own
     * prompt and the card's task.
     */
    "prompt"?: string;

    /**
     * Crew is who may work this stage. Not an assignment but a list of who is
     * allowed at all: the card chooses among them (see PickAgent).
     */
    "crew"?: string[] | null;

    /**
     * MaxRunning bounds how many cards this stage works at once. Zero means no
     * limit of its own; the machine-wide limit still applies.
     */
    "maxRunning"?: number;

    /**
     * Final says a card reaching this stage is done. It runs nothing and leads
     * nowhere.
     */
    "final"?: boolean;

    /**
     * Writes are the properties this stage leaves on the card — its declared
     * outputs, and what makes a transition on a property deterministic rather
     * than hopeful: the edge that asks about «Verdict» points at the stage that
     * must produce it.
     * 
     * A session delivers them in its closing words, in the shape the brief asks
     * for (see engine.StageOutputs); a stage working in a terminal puts them in
     * the same call that says it has finished, since a CLI has no closing words
     * to read. Either way a required one is refused without: the stage cannot
     * end until the value stands.
     */
    "writes"?: PropertyWrite[] | null;

    /**
     * Reads are the properties whose values open this stage's brief: what an
     * earlier stage wrote — a preview address, a reviewer's verdict — handed to
     * the agent instead of hoping it goes looking. Empty is not "nothing": it
     * falls back to whatever the stages ahead of this one on the route declare
     * they write (UpstreamWrites), because a value already on the card is on the
     * card, and asking somebody to tick it again on every later stage is asking
     * for the same fact twice. A list of its own is how a stage says "not all of
     * it", and clearing it gives the graph's answer back.
     */
    "reads"?: string[] | null;

    /**
     * Screens are what a person looking at this step sees: the notes, the
     * terminal, the browser that belong to it. They are declared by any stage,
     * including one that runs nothing — unlike Writes and Reads, and that is a
     * decision rather than an oversight (docs/system.md §12.4). The subject
     * differs: an output is about the card and there is nobody to produce one
     * on a waiting stage, while a screen is about the person, and the review
     * stage is exactly where the preview has to be open.
     * 
     * The agent's own screen — its terminal, or the stream of a session — is
     * not declared: it exists whenever what it shows exists.
     */
    "screens"?: Screen[] | null;

    /**
     * X and Y are where the editor left the stage on its canvas. Absent means
     * "lay it out for me" — a flow written by hand never has to place anything.
     */
    "x"?: number;
    "y"?: number;
}

/**
 * Trigger describes one edge trigger. The list doubles as the editor's
 * dropdown, so the UI can never offer a trigger the engine does not implement;
 * what it is called is the UI's, keyed by Kind.
 */
export interface Trigger {
    "kind": string;
    "source": string;
}

/**
 * Wait is one thing a parked card is waiting for: the event, and the condition
 * that makes it the one — «Approved» = «Yes», not just "a property changed".
 */
export interface Wait {
    "on": string;
    "if"?: Cond | null;
}
