// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as msg$0 from "../msg/models.js";

/**
 * AdapterStatus is what the UI shows next to a kind.
 * 
 * Answering "is this agent usable on this machine" in the agents dialog is the
 * point. A missing adapter otherwise surfaces as a session that fails at its
 * first turn, on a card, minutes after somebody configured the agent — while
 * the fact was knowable the moment the dialog was opened.
 */
export interface AdapterStatus {
    "kind": string;

    /**
     * Package is the npm package that provides the adapter, empty for a kind
     * whose CLI is installed some other way.
     */
    "package"?: string;

    /**
     * Path is the adapter binary we found, empty when there is none.
     */
    "path"?: string;

    /**
     * Ready reports that a session of this kind can start right now.
     */
    "ready": boolean;

    /**
     * ViaNPX marks a kind that is not installed but will be run through npx —
     * it works, only the first run pays for the download.
     */
    "viaNpx"?: boolean;

    /**
     * Detail says what is missing, with what a person needs to act on.
     */
    "detail"?: msg$0.Msg | null;

    /**
     * Terminal reports that a stage can be *worked in a terminal* by this kind,
     * which is a different question from Ready and has a different answer: the
     * vendor adapter and the vendor's interactive CLI are two programs, and a
     * machine can have one without the other (docs/system.md §4.1.1).
     */
    "terminal": boolean;

    /**
     * TerminalDetail says why not, or what it will run.
     */
    "terminalDetail"?: msg$0.Msg | null;
}

/**
 * Answer is the reply. An answer with neither an option nor text is a refusal,
 * which is also what an agent gets when the application closes with the
 * question still open.
 */
export interface Answer {
    "optionId"?: string;
    "text"?: string;
    "declined"?: boolean;
}

/**
 * Attention is one thing waiting for a person. There are two kinds of it, and
 * which one a row is, is said by whether it carries a question.
 * 
 * A **question** is the protocol asking: an ACP session sent a permission
 * request or an elicitation, and the agent is waiting on the answer with its
 * turn still open. It has options, and answering it here is what releases the
 * agent.
 * 
 * A **silent terminal** is the other one, and it is not answerable from here on
 * purpose: the agent asked inside its own interface, where the question was
 * never ours to carry (docs/system.md §4.1.1). What the row says is «go and
 * look», and the answer is typed where it was asked.
 * 
 * It is a separate shape from Question so that the panel and the mark on a card
 * read the same list — one bookkeeping of the fact, not two.
 */
export interface Attention {
    "key": string;
    "questionId": string;
    "cardId"?: string;
    "cardTitle"?: string;
    "agent"?: string;

    /**
     * Kind is which question it is, on a question: a permission is worded
     * around the tool it is for, a form around the agent's own message.
     */
    "kind"?: QuestionKind;
    "tool"?: string;
    "text"?: string;
    "options"?: QuestionOption[] | null;
    "freeText"?: boolean;

    /**
     * Awaiting is false in an event that says a wait ended; the list only ever
     * carries true.
     */
    "awaiting": boolean;
    "since"?: string;

    /**
     * Worktree is set on the third kind: a closed card's separate working
     * tree, and whether to remove it (workspace.go). Branch is what stays
     * either way; Dirty says removing it loses uncommitted changes.
     */
    "worktree"?: string;
    "branch"?: string;
    "dirty"?: boolean;
}

/**
 * PastSession is one conversation as the agent lists it.
 */
export interface PastSession {
    "id": string;
    "cwd": string;
    "title"?: string;

    /**
     * UpdatedAt is what the agent says. For claude it is the file's mtime, which
     * the CLI also bumps when it merely annotates an old conversation, so it
     * orders roughly rather than exactly.
     */
    "updatedAt": string;
}

/**
 * Question is what a card shows and what the UI answers.
 */
export interface Question {
    "id": string;
    "sessionId": string;
    "cardId"?: string;
    "cardTitle"?: string;
    "stageId"?: string;
    "agent"?: string;
    "kind": QuestionKind;

    /**
     * Text is the question itself: the tool call's title for a permission, the
     * agent's message for a form.
     */
    "text": string;
    "tool"?: string;
    "options"?: QuestionOption[] | null;

    /**
     * FreeText says an answer may be typed instead of chosen. The claude
     * adapter always offers one beside its options, and a form with no options
     * at all is nothing but this.
     */
    "freeText": boolean;
    "askedAt": string;
}

/**
 * QuestionKind says which of the two arrived, because they are answered
 * differently — one picks a permission option, the other fills in a form.
 */
export enum QuestionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuestionPermission = "permission",
    QuestionForm = "form",
};

/**
 * QuestionOption is one answer the agent offered.
 */
export interface QuestionOption {
    "id": string;
    "label": string;
    "description"?: string;

    /**
     * Kind is the permission option's own kind (allow_once, reject_always, …),
     * kept because "always" is remembered for the rest of the session.
     */
    "kind"?: string;
}
