// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AdapterStatus is what the UI shows next to a kind.
 * 
 * Answering "is this agent usable on this machine" in the agents dialog is the
 * point. A missing adapter otherwise surfaces as a session that fails at its
 * first turn, on a card, minutes after somebody configured the agent — while
 * the fact was knowable the moment the dialog was opened.
 */
export class AdapterStatus {
    "kind": string;

    /**
     * Package is the npm package that provides the adapter, empty for a kind
     * whose CLI is installed some other way.
     */
    "package"?: string;

    /**
     * Path is the adapter binary we found, empty when there is none.
     */
    "path"?: string;

    /**
     * Ready reports that a session of this kind can start right now.
     */
    "ready": boolean;

    /**
     * ViaNPX marks a kind that is not installed but will be run through npx —
     * it works, only the first run pays for the download.
     */
    "viaNpx"?: boolean;

    /**
     * Detail says what is missing, in the words a person needs to act on.
     */
    "detail"?: string;

    /** Creates a new AdapterStatus instance. */
    constructor($$source: Partial<AdapterStatus> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdapterStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AdapterStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdapterStatus($$parsedSource as Partial<AdapterStatus>);
    }
}

/**
 * Answer is the reply. An answer with neither an option nor text is a refusal,
 * which is also what an agent gets when the application closes with the
 * question still open.
 */
export class Answer {
    "optionId"?: string;
    "text"?: string;
    "declined"?: boolean;

    /** Creates a new Answer instance. */
    constructor($$source: Partial<Answer> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Answer instance from a string or object.
     */
    static createFrom($$source: any = {}): Answer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Answer($$parsedSource as Partial<Answer>);
    }
}

/**
 * Attention is one thing waiting for a person. There is one kind of it, and it
 * is the protocol asking: an ACP session sent a permission request or an
 * elicitation, and the agent is waiting on the answer with its turn still open.
 * 
 * It is a separate shape from Question so that the panel and the mark on a card
 * read the same list — one bookkeeping of the fact, not two.
 */
export class Attention {
    "key": string;
    "questionId": string;
    "cardId"?: string;
    "cardTitle"?: string;
    "agent"?: string;
    "tool"?: string;
    "text"?: string;
    "options"?: QuestionOption[];
    "freeText"?: boolean;

    /**
     * Awaiting is false in an event that says a wait ended; the list only ever
     * carries true.
     */
    "awaiting": boolean;
    "since"?: string;

    /** Creates a new Attention instance. */
    constructor($$source: Partial<Attention> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("questionId" in $$source)) {
            this["questionId"] = "";
        }
        if (!("awaiting" in $$source)) {
            this["awaiting"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attention instance from a string or object.
     */
    static createFrom($$source: any = {}): Attention {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField7_0($$parsedSource["options"]);
        }
        return new Attention($$parsedSource as Partial<Attention>);
    }
}

/**
 * Question is what a card shows and what the UI answers.
 */
export class Question {
    "id": string;
    "sessionId": string;
    "cardId"?: string;
    "cardTitle"?: string;
    "stageId"?: string;
    "agent"?: string;
    "kind": QuestionKind;

    /**
     * Text is the question itself: the tool call's title for a permission, the
     * agent's message for a form.
     */
    "text": string;
    "tool"?: string;
    "options"?: QuestionOption[];

    /**
     * FreeText says an answer may be typed instead of chosen. The claude
     * adapter always offers one beside its options, and a form with no options
     * at all is nothing but this.
     */
    "freeText": boolean;
    "askedAt": string;

    /** Creates a new Question instance. */
    constructor($$source: Partial<Question> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = QuestionKind.$zero;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("freeText" in $$source)) {
            this["freeText"] = false;
        }
        if (!("askedAt" in $$source)) {
            this["askedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Question instance from a string or object.
     */
    static createFrom($$source: any = {}): Question {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField9_0($$parsedSource["options"]);
        }
        return new Question($$parsedSource as Partial<Question>);
    }
}

/**
 * QuestionKind says which of the two arrived, because they are answered
 * differently — one picks a permission option, the other fills in a form.
 */
export enum QuestionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuestionPermission = "permission",
    QuestionForm = "form",
};

/**
 * QuestionOption is one answer the agent offered.
 */
export class QuestionOption {
    "id": string;
    "label": string;
    "description"?: string;

    /**
     * Kind is the permission option's own kind (allow_once, reject_always, …),
     * kept because "always" is remembered for the rest of the session.
     */
    "kind"?: string;

    /** Creates a new QuestionOption instance. */
    constructor($$source: Partial<QuestionOption> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionOption($$parsedSource as Partial<QuestionOption>);
    }
}

// Private type creation functions
const $$createType0 = QuestionOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
