// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AdapterStatus is what the UI shows next to a kind.
 * 
 * Answering "is this agent usable on this machine" in the agents dialog is the
 * point. A missing adapter otherwise surfaces as a session that fails at its
 * first turn, on a card, minutes after somebody configured the agent — while
 * the fact was knowable the moment the dialog was opened.
 */
export interface AdapterStatus {
    "kind": string;

    /**
     * Package is the npm package that provides the adapter, empty for a kind
     * whose CLI is installed some other way.
     */
    "package"?: string;

    /**
     * Path is the adapter binary we found, empty when there is none.
     */
    "path"?: string;

    /**
     * Ready reports that a session of this kind can start right now.
     */
    "ready": boolean;

    /**
     * ViaNPX marks a kind that is not installed but will be run through npx —
     * it works, only the first run pays for the download.
     */
    "viaNpx"?: boolean;

    /**
     * Detail says what is missing, in the words a person needs to act on.
     */
    "detail"?: string;
}

/**
 * Answer is the reply. An answer with neither an option nor text is a refusal,
 * which is also what an agent gets when the application closes with the
 * question still open.
 */
export interface Answer {
    "optionId"?: string;
    "text"?: string;
    "declined"?: boolean;
}

/**
 * Attention is one thing waiting for a person. There is one kind of it, and it
 * is the protocol asking: an ACP session sent a permission request or an
 * elicitation, and the agent is waiting on the answer with its turn still open.
 * 
 * It is a separate shape from Question so that the panel and the mark on a card
 * read the same list — one bookkeeping of the fact, not two.
 */
export interface Attention {
    "key": string;
    "questionId": string;
    "cardId"?: string;
    "cardTitle"?: string;
    "agent"?: string;
    "tool"?: string;
    "text"?: string;
    "options"?: QuestionOption[] | null;
    "freeText"?: boolean;

    /**
     * Awaiting is false in an event that says a wait ended; the list only ever
     * carries true.
     */
    "awaiting": boolean;
    "since"?: string;
}

/**
 * Question is what a card shows and what the UI answers.
 */
export interface Question {
    "id": string;
    "sessionId": string;
    "cardId"?: string;
    "cardTitle"?: string;
    "stageId"?: string;
    "agent"?: string;
    "kind": QuestionKind;

    /**
     * Text is the question itself: the tool call's title for a permission, the
     * agent's message for a form.
     */
    "text": string;
    "tool"?: string;
    "options"?: QuestionOption[] | null;

    /**
     * FreeText says an answer may be typed instead of chosen. The claude
     * adapter always offers one beside its options, and a form with no options
     * at all is nothing but this.
     */
    "freeText": boolean;
    "askedAt": string;
}

/**
 * QuestionKind says which of the two arrived, because they are answered
 * differently — one picks a permission option, the other fills in a form.
 */
export enum QuestionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QuestionPermission = "permission",
    QuestionForm = "form",
};

/**
 * QuestionOption is one answer the agent offered.
 */
export interface QuestionOption {
    "id": string;
    "label": string;
    "description"?: string;

    /**
     * Kind is the permission option's own kind (allow_once, reject_always, …),
     * kept because "always" is remembered for the rest of the session.
     */
    "kind"?: string;
}
