// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CardFlow is the whole answer for one card.
 */
export class CardFlow {
    "flowId": string;
    "flowName": string;
    "stages": CardStage[];
    "stageId": string;
    "since": string;

    /**
     * WaitingFor is what the stage is waiting on, in a person's words and with
     * the conditions spelled out. Empty on a stage that runs something.
     */
    "waitingFor"?: string[];

    /**
     * waiting for a place on the stage
     */
    "queued"?: boolean;

    /**
     * a session of this stage is working now
     */
    "running"?: boolean;

    /** Creates a new CardFlow instance. */
    constructor($$source: Partial<CardFlow> = {}) {
        if (!("flowId" in $$source)) {
            this["flowId"] = "";
        }
        if (!("flowName" in $$source)) {
            this["flowName"] = "";
        }
        if (!("stages" in $$source)) {
            this["stages"] = [];
        }
        if (!("stageId" in $$source)) {
            this["stageId"] = "";
        }
        if (!("since" in $$source)) {
            this["since"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CardFlow instance from a string or object.
     */
    static createFrom($$source: any = {}): CardFlow {
        const $$createField2_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField2_0($$parsedSource["stages"]);
        }
        if ("waitingFor" in $$parsedSource) {
            $$parsedSource["waitingFor"] = $$createField5_0($$parsedSource["waitingFor"]);
        }
        return new CardFlow($$parsedSource as Partial<CardFlow>);
    }
}

/**
 * CardStage is one stage of the flow as the card sees it.
 */
export class CardStage {
    "id": string;
    "name": string;
    "action": string;
    "crew"?: string[];
    "final"?: boolean;
    "current": boolean;

    /**
     * the card has already been through it
     */
    "done": boolean;

    /** Creates a new CardStage instance. */
    constructor($$source: Partial<CardStage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CardStage instance from a string or object.
     */
    static createFrom($$source: any = {}): CardStage {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("crew" in $$parsedSource) {
            $$parsedSource["crew"] = $$createField3_0($$parsedSource["crew"]);
        }
        return new CardStage($$parsedSource as Partial<CardStage>);
    }
}

/**
 * FlowOverview is one flow and where its cards are along it.
 */
export class FlowOverview {
    "flow": model$0.Flow;
    "stages": StageLoad[];
    "cards": number;

    /** Creates a new FlowOverview instance. */
    constructor($$source: Partial<FlowOverview> = {}) {
        if (!("flow" in $$source)) {
            this["flow"] = (new model$0.Flow());
        }
        if (!("stages" in $$source)) {
            this["stages"] = [];
        }
        if (!("cards" in $$source)) {
            this["cards"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlowOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): FlowOverview {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flow" in $$parsedSource) {
            $$parsedSource["flow"] = $$createField0_0($$parsedSource["flow"]);
        }
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField1_0($$parsedSource["stages"]);
        }
        return new FlowOverview($$parsedSource as Partial<FlowOverview>);
    }
}

/**
 * StageLoad is how busy one stage is right now.
 */
export class StageLoad {
    "stageId": string;

    /**
     * cards standing on it
     */
    "cards": number;

    /**
     * of those, waiting for a place
     */
    "queued": number;

    /**
     * of those, being worked on now
     */
    "running": number;

    /** Creates a new StageLoad instance. */
    constructor($$source: Partial<StageLoad> = {}) {
        if (!("stageId" in $$source)) {
            this["stageId"] = "";
        }
        if (!("cards" in $$source)) {
            this["cards"] = 0;
        }
        if (!("queued" in $$source)) {
            this["queued"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StageLoad instance from a string or object.
     */
    static createFrom($$source: any = {}): StageLoad {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StageLoad($$parsedSource as Partial<StageLoad>);
    }
}

// Private type creation functions
const $$createType0 = CardStage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = model$0.Flow.createFrom;
const $$createType4 = StageLoad.createFrom;
const $$createType5 = $Create.Array($$createType4);
