// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CardFlow is the whole answer for one card.
 */
export interface CardFlow {
    "flowId": string;
    "flowName": string;
    "stages": CardStage[] | null;
    "stageId": string;
    "since": string;

    /**
     * WaitingFor is what the stage is waiting on, in a person's words and with
     * the conditions spelled out. Empty on a stage that runs something.
     */
    "waitingFor"?: string[] | null;

    /**
     * waiting for a place on the stage
     */
    "queued"?: boolean;

    /**
     * a session of this stage is working now
     */
    "running"?: boolean;

    /**
     * Marks are the moves a person can make from here — see model.Mark. Empty
     * wherever the flow does not offer one, which is every stage that decides
     * for itself.
     */
    "marks"?: model$0.Mark[] | null;
}

/**
 * CardStage is one stage of the flow as the card sees it.
 */
export interface CardStage {
    "id": string;
    "name": string;
    "action": string;
    "crew"?: string[] | null;
    "final"?: boolean;
    "current": boolean;

    /**
     * the card has already been through it
     */
    "done": boolean;
}

/**
 * FlowOverview is one flow and where its cards are along it.
 */
export interface FlowOverview {
    "flow": model$0.Flow;
    "stages": StageLoad[] | null;
    "cards": number;
}

/**
 * RibbonView is one card in work, shown as a strip.
 */
export interface RibbonView {
    /**
     * ID is the ribbon's identity for the UI, which reconciles the stack by it.
     * It is the card's id: one card in work is one ribbon, and there is no
     * other kind.
     */
    "id": string;
    "cardId": string;
    "title": string;
    "flowId": string;
    "flowName": string;

    /**
     * StageName and Running are what a ribbon says about itself from outside —
     * enough for the indicator without reading the strip.
     */
    "stageName"?: string;
    "running"?: boolean;
    "segments": Segment[] | null;

    /**
     * FocusID is where the ribbon flies when a step ends: the first screen of
     * the segment the card stands in.
     */
    "focusId"?: string;
}

/**
 * ScreenView is one window on the strip.
 */
export interface ScreenView {
    /**
     * ID is derived rather than stored, and stable across re-reads: the UI
     * keys its panes by it, and a pane that loses its identity is an iframe
     * that reloads and a cursor that jumps out of the notes.
     */
    "id": string;
    "kind": string;
    "title": string;

    /**
     * Ref is what to open, with the card's properties already put in.
     */
    "ref"?: string;

    /**
     * Waiting names the properties that had no value yet. The screen stands
     * blank and says so rather than opening nothing and staying silent.
     */
    "waiting"?: string[] | null;

    /**
     * SessionID is set on the screen that belongs to an agent's run: the
     * terminal it was worked in, or the stream of a session.
     */
    "sessionId"?: string;
}

/**
 * Segment is one visit to one stage: everything that happened between this
 * transition and the next.
 */
export interface Segment {
    /**
     * ID is the segment's identity for the UI, which reconciles the strip by
     * it: without one, a re-read would rebuild every pane and the iframe of a
     * running preview would reload on every step the agent takes.
     */
    "id": string;

    /**
     * EventID is the flow_event this segment is, and the first half of every
     * screen id under it.
     */
    "eventId": number;
    "stageId": string;
    "stageName": string;
    "on"?: string;
    "detail"?: string;
    "enteredAt": string;
    "current": boolean;

    /**
     * Gone says the stage was removed from the flow while the card was on it.
     * The segment stays — what happened happened — and says why it is empty.
     */
    "gone"?: boolean;
    "screens"?: ScreenView[] | null;
}

/**
 * StageLoad is how busy one stage is right now.
 */
export interface StageLoad {
    "stageId": string;

    /**
     * cards standing on it
     */
    "cards": number;

    /**
     * of those, waiting for a place
     */
    "queued": number;

    /**
     * of those, being worked on now
     */
    "running": number;
}
