// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as msg$0 from "../msg/models.js";

/**
 * CardFlow is the whole answer for one card.
 */
export interface CardFlow {
    "flowId": string;
    "flowName": string;
    "stages": CardStage[] | null;
    "stageId": string;
    "since": string;

    /**
     * WaitingFor is what the stage is waiting on: the events, and the conditions
     * that make them the ones. Empty on a stage that runs something.
     */
    "waitingFor"?: model$0.Wait[] | null;

    /**
     * waiting for a place on the stage
     */
    "queued"?: boolean;

    /**
     * a session of this stage is working now
     */
    "running"?: boolean;

    /**
     * Marks are the moves a person can make from here — see model.Mark. Empty
     * wherever the flow does not offer one, which is every stage that decides
     * for itself.
     */
    "marks"?: model$0.Mark[] | null;
}

/**
 * CardStage is one stage of the flow as the card sees it.
 */
export interface CardStage {
    "id": string;
    "name": string;
    "action": string;
    "crew"?: string[] | null;
    "final"?: boolean;
    "current": boolean;

    /**
     * the card has already been through it
     */
    "done": boolean;
}

/**
 * FlowOverview is one flow and where its cards are along it.
 */
export interface FlowOverview {
    "flow": model$0.Flow;
    "stages": StageLoad[] | null;
    "cards": number;
}

/**
 * Notice is a journal entry the strip shows: why the card stands here, or why
 * the step broke.
 */
export interface Notice {
    /**
     * Kind tells a problem from a reviewer's remarks and from news of the
     * source: all three explain the segment, but one is the application saying
     * it stopped, one a person saying what to fix, and one the MR having moved
     * under the person reading it.
     */
    "kind": model$0.EntryKind;
    "msg"?: msg$0.Msg | null;
    "text"?: string;
    "author"?: string;
    "at": string;
}

/**
 * RibbonView is one card in work, shown as a strip.
 */
export interface RibbonView {
    /**
     * ID is the ribbon's identity for the UI, which reconciles the stack by it.
     * It is the card's id: one card in work is one ribbon, and there is no
     * other kind.
     */
    "id": string;
    "cardId": string;
    "title": string;
    "flowId": string;
    "flowName": string;

    /**
     * Project is the card's project, the workspace the ribbon is shown in.
     */
    "project"?: string;

    /**
     * StageName and Running are what a ribbon says about itself from outside —
     * enough for the indicator without reading the strip.
     */
    "stageName"?: string;
    "running"?: boolean;
    "segments": Segment[] | null;

    /**
     * FocusID is where the ribbon flies when a step ends: the first screen of
     * the segment the card stands in.
     */
    "focusId"?: string;
}

/**
 * ScreenView is one window on the strip.
 */
export interface ScreenView {
    /**
     * ID is derived rather than stored, and stable across re-reads: the UI
     * keys its panes by it, and a pane that loses its identity is an iframe
     * that reloads and a cursor that jumps out of the notes.
     */
    "id": string;
    "kind": string;

    /**
     * Title is what the stage called the screen. Empty when it did not, and on
     * an agent's own screen, which the UI names by its kind and Agent.
     */
    "title"?: string;

    /**
     * Agent is whose run the screen shows, on an agent's own screen.
     */
    "agent"?: string;

    /**
     * Ref is what to open, with the card's properties already put in.
     */
    "ref"?: string;

    /**
     * Waiting names the properties that had no value yet. The screen stands
     * blank and says so rather than opening nothing and staying silent.
     */
    "waiting"?: string[] | null;

    /**
     * SessionID is set on the screen that belongs to an agent's run: the
     * terminal it was worked in, or the stream of a session.
     */
    "sessionId"?: string;

    /**
     * Report is what the run said its step came to. A terminal has nowhere
     * else to show it: the agent hands it over in a tool call, not on screen.
     */
    "report"?: msg$0.Msg | null;

    /**
     * Paused is set on the last run of the stage the card stands on when the
     * application closed on it: the screen offers to continue it (Continue).
     */
    "paused"?: boolean;
}

/**
 * Segment is one visit to one stage: everything that happened between this
 * transition and the next.
 */
export interface Segment {
    /**
     * ID is the segment's identity for the UI, which reconciles the strip by
     * it: without one, a re-read would rebuild every pane and the iframe of a
     * running preview would reload on every step the agent takes.
     */
    "id": string;

    /**
     * EventID is the flow_event this segment is, and the first half of every
     * screen id under it.
     */
    "eventId": number;
    "stageId": string;
    "stageName": string;
    "on"?: string;
    "detail"?: msg$0.Msg | null;
    "enteredAt": string;
    "current": boolean;

    /**
     * Gone says the stage was removed from the flow while the card was on it.
     * The segment stays — what happened happened — and says why it is empty.
     */
    "gone"?: boolean;
    "screens"?: ScreenView[] | null;

    /**
     * Marks are the moves a person can make from here, and only the segment
     * the card stands in has any: a step already over is not waiting for an
     * answer.
     * 
     * They are on the strip because the strip is the whole window (docs/system.md
     * §12.5). A review stage shows what it is asking about — the diff, the
     * preview — and sending the person to the card screen to answer would mean
     * leaving the thing they are answering about.
     */
    "marks"?: model$0.Mark[] | null;

    /**
     * Problems are why the card stood or broke during this visit, oldest first.
     */
    "problems"?: Notice[] | null;
}

/**
 * StageLoad is how busy one stage is right now.
 */
export interface StageLoad {
    "stageId": string;

    /**
     * cards standing on it
     */
    "cards": number;

    /**
     * of those, waiting for a place
     */
    "queued": number;

    /**
     * of those, being worked on now
     */
    "running": number;
}
