// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Profile is one way to start a project.
 */
export interface Profile {
    "kind": string;

    /**
     * Tool is what the project was recognised by — «vite», «compose»,
     * «flutter» — shown as it is, next to the kind.
     */
    "tool"?: string;

    /**
     * Dir is the subfolder the project was found in, relative to the card's
     * folder, when it is not the folder itself: a repository with the
     * frontend in frontend/ is started from there.
     */
    "dir"?: string;
    "command": string;

    /**
     * URL is where the project is expected to answer before it has said so
     * itself. What it prints wins (Address).
     */
    "url"?: string;
}

/**
 * Request is one call to a started service, as the run screen composed it.
 */
export interface Request {
    "method": string;
    "url": string;

    /**
     * «Name: value», one per line
     */
    "headers"?: string;
    "body"?: string;
}

/**
 * Response is what came back, cut to what a screen can show.
 */
export interface Response {
    "status": string;
    "code": number;
    "headers": string;
    "body": string;
    "truncated"?: boolean;
    "millis": number;
}
