// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Session is one recorded run of an agent against one card on one stage.
 */
export class Session {
    "id": string;
    "cardId": string;
    "flowId"?: string;
    "stageId"?: string;
    "agentName": string;
    "agentKind": string;
    "acpSessionId"?: string;
    "status": SessionStatus;
    "cwd"?: string;
    "startedAt": string;
    "finishedAt"?: string;
    "errorText"?: string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("cardId" in $$source)) {
            this["cardId"] = "";
        }
        if (!("agentName" in $$source)) {
            this["agentName"] = "";
        }
        if (!("agentKind" in $$source)) {
            this["agentKind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = SessionStatus.$zero;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}

/**
 * SessionStatus is the lifecycle state of an agent session.
 */
export enum SessionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusRunning = "running",

    /**
     * stopped on a question, waiting for a person
     */
    StatusAsking = "asking",
    StatusDone = "done",
    StatusFailed = "failed",
    StatusCancelled = "cancelled",
};
