// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Session is one recorded run of an agent against one card on one stage.
 */
export interface Session {
    "id": string;
    "cardId": string;
    "flowId"?: string;
    "stageId"?: string;
    "agentName": string;
    "agentKind": string;
    "acpSessionId"?: string;
    "status": SessionStatus;
    "cwd"?: string;
    "startedAt": string;
    "finishedAt"?: string;
    "errorText"?: string;
}

/**
 * SessionEvent is one line of a session's stream.
 */
export interface SessionEvent {
    "seq": number;
    "kind": string;
    "payload": string;
    "createdAt": string;
}

/**
 * SessionStatus is the lifecycle state of an agent session.
 */
export enum SessionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusRunning = "running",

    /**
     * stopped on a question, waiting for a person
     */
    StatusAsking = "asking",
    StatusDone = "done",
    StatusFailed = "failed",
    StatusCancelled = "cancelled",
};
