// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RemoteOption is one of a repository's remotes, as the connect form offers
 * it: the name, the address, and the server and repository it suggests.
 */
export interface RemoteOption {
    "name": string;
    "url": string;
    "server"?: string;
    "repository"?: string;
}
