// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Msg is one thing to tell a person.
 */
export interface Msg {
    "code": string;

    /**
     * Args are the values the wording needs — names, paths, counts — keyed by
     * what they are. Never words of their own: a value here is shown as it is.
     */
    "args"?: { [_ in string]?: string } | null;

    /**
     * Cause is the reason under this one, when there is one worth telling: a
     * stage that is refused because of one of its screens says both.
     */
    "cause"?: Msg | null;
}
