// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Diff is everything one diff screen shows.
 */
export interface Diff {
    /**
     * Root is the repository the folder belongs to, which is not always the
     * folder itself — a card may work in a subdirectory of one.
     */
    "root": string;

    /**
     * Ref is what was compared, as the screen asked for it. Empty is the
     * working copy against the last commit, or against Base when there is one.
     */
    "ref"?: string;

    /**
     * Branch, Base and Commits say what an empty ref came to on a card with a
     * branch: the branch checked out, what it was cut from, and how many
     * commits it has since. Without them the header could only say "not
     * committed" about work that mostly is.
     */
    "branch"?: string;
    "base"?: string;
    "commits"?: number;
    "files": File[] | null;

    /**
     * Truncated says the patch was bigger than the screen keeps. The counts on
     * each file stay true regardless: they are what a person decides by.
     */
    "truncated"?: boolean;
}

/**
 * File is one file in the patch.
 */
export interface File {
    "path": string;

    /**
     * OldPath is set only for a rename: elsewhere it would repeat Path.
     */
    "oldPath"?: string;
    "status": string;

    /**
     * Binary files have no hunks and never will: git says they differ and
     * stops, and so do we — a screen that renders bytes as text is a screen
     * nobody can read.
     */
    "binary"?: boolean;
    "added": number;
    "removed": number;
    "hunks"?: Hunk[] | null;
}

/**
 * Hunk is one changed region. Heading is what git puts after the @@ — usually
 * the enclosing function — and it is kept because it is the only thing telling
 * a reader where in the file they are.
 */
export interface Hunk {
    "header": string;
    "heading"?: string;
    "lines": Line[] | null;
}

/**
 * Line is one row of a hunk. Old and New are the line numbers on each side, and
 * zero means the line is not on that side — which is what lets the viewer show
 * two columns of numbers without counting them again.
 */
export interface Line {
    "kind": string;
    "text": string;
    "old"?: number;
    "new"?: number;
}
