// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * API is what the UI calls. One service rather than several: the screens do not
 * divide along the same lines the packages do — the card screen needs the flow,
 * the sessions and the open question at once — and a facade that hands back
 * whole screens is less to keep in step than four that hand back fragments.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as acp$0 from "../acp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCard files a card somebody typed straight into the inbox.
 */
export function AddCard(sourceName: string, title: string, body: string): $CancellablePromise<model$0.Card> {
    return $Call.ByID(3801214340, sourceName, title, body);
}

/**
 * AddComment writes a person's note into a card's history.
 */
export function AddComment(cardID: string, text: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(2030529371, cardID, text);
}

/**
 * AddItem files an item into a source by hand. It goes through the source's own
 * file rather than straight into a card, so a hand-added item is an item like
 * any other: it meets the same rules and survives the file being read again.
 */
export function AddItem(sourceName: string, title: string, body: string): $CancellablePromise<model$0.InboxGroup[] | null> {
    return $Call.ByID(1502436789, sourceName, title, body);
}

/**
 * Agents is the registry with the adapter check beside it, because "is this
 * agent usable here" is the question a person opens that screen with.
 */
export function Agents(): $CancellablePromise<$models.AgentsView> {
    return $Call.ByID(4132736297);
}

/**
 * Answer delivers a person's answer to an agent's question.
 */
export function Answer(questionID: string, answer: acp$0.Answer): $CancellablePromise<void> {
    return $Call.ByID(4238054837, questionID, answer);
}

/**
 * Attention is every question an agent is waiting on, oldest first.
 */
export function Attention(): $CancellablePromise<acp$0.Attention[] | null> {
    return $Call.ByID(978520023);
}

/**
 * CancelCard stops whatever is running for a card. A cancelled session produces
 * no outcome: the person who stopped it decides what happens next.
 */
export function CancelCard(cardID: string): $CancellablePromise<void> {
    return $Call.ByID(1480875471, cardID);
}

/**
 * Card is everything about one card.
 */
export function Card(cardID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(1660277701, cardID);
}

/**
 * CheckForUpdate asks the release feed. The answer arrives as the update event,
 * so the screen draws the checking state from the same place it draws
 * everything else rather than from a promise.
 */
export function CheckForUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1344566209);
}

/**
 * CloseTerminal ends one shell. A person closing a terminal means the process
 * in it, not just the window onto it — the ribbon has no windows to close.
 */
export function CloseTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByID(575378589, id);
}

/**
 * DeleteAgent removes an entry, refusing while a flow still names it: a stage
 * whose crew is nobody is a card that silently never starts, and finding that
 * out here is better than finding it out mid-run.
 */
export function DeleteAgent(name: string): $CancellablePromise<void> {
    return $Call.ByID(2879232337, name);
}

/**
 * DeleteFlow removes a flow. Cards standing on it stop advancing by themselves
 * and say so; nothing else happens to them.
 */
export function DeleteFlow(flowID: string): $CancellablePromise<void> {
    return $Call.ByID(2555422584, flowID);
}

/**
 * DeleteProject removes one, refusing while a card still names it.
 */
export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(1914798965, id);
}

/**
 * DeleteSource removes a source. The cards it brought stay: they are work, and
 * the source is only where they came from.
 */
export function DeleteSource(name: string): $CancellablePromise<void> {
    return $Call.ByID(797133365, name);
}

/**
 * Done is the closed cards, newest first.
 */
export function Done(): $CancellablePromise<model$0.Card[] | null> {
    return $Call.ByID(669172479);
}

/**
 * DropCard files a card away without doing it. The card is kept — what was
 * dropped and why is the sort of thing somebody asks about later.
 */
export function DropCard(cardID: string): $CancellablePromise<void> {
    return $Call.ByID(216846176, cardID);
}

/**
 * EditCard changes a card's own text.
 */
export function EditCard(cardID: string, title: string, body: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(2223589865, cardID, title, body);
}

/**
 * FlowCards lists the cards travelling a flow, with the stage each stands on.
 */
export function FlowCards(flowID: string): $CancellablePromise<$models.StageCard[] | null> {
    return $Call.ByID(3466565678, flowID);
}

/**
 * FlowOverview is one flow and where its cards are along it.
 */
export function FlowOverview(flowID: string): $CancellablePromise<engine$0.FlowOverview> {
    return $Call.ByID(283715336, flowID);
}

/**
 * Flows is every flow, whole.
 */
export function Flows(): $CancellablePromise<model$0.Flow[] | null> {
    return $Call.ByID(2493457172);
}

/**
 * InWork is every card currently travelling a flow.
 */
export function InWork(): $CancellablePromise<$models.CardSummary[] | null> {
    return $Call.ByID(2027618605);
}

/**
 * Inbox is everything waiting to be taken into work, grouped by what brought it.
 */
export function Inbox(): $CancellablePromise<model$0.InboxGroup[] | null> {
    return $Call.ByID(64525769);
}

/**
 * InstallUpdate downloads what the last check found, checks its signature
 * against the key this binary was built with, and stages it. Nothing is
 * replaced until RestartToUpdate.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1867268347);
}

/**
 * MarkOutcome is a person answering for a stage that runs nothing: «прошло» or
 * «не прошло», put on the card so the flow sees it and moves.
 * 
 * It goes through SetProp rather than straight to the store, and that is the
 * point: the engine's own write of the outcome is silent, because the machine
 * recording a fact must not set the card's own automation off. This one has to
 * — it is a person's edit, and it goes the way a person's edit goes.
 */
export function MarkOutcome(cardID: string, value: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(4204052738, cardID, value);
}

/**
 * MoveTo puts a card on a stage by hand. A person is always above the graph.
 */
export function MoveTo(cardID: string, stageID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(3200309791, cardID, stageID);
}

/**
 * OpenTerminal starts the shell behind one terminal screen, or hands back the
 * one already running there.
 * 
 * Keyed by screen: a screen id is derived from the card's journal and does not
 * change, so re-reading the ribbon — which happens on every step the agent
 * takes — must not leave a second shell behind each time.
 */
export function OpenTerminal(cardID: string, screenID: string, command: string): $CancellablePromise<$models.TerminalHandle> {
    return $Call.ByID(3998944851, cardID, screenID, command);
}

/**
 * PickFolder opens the system's own folder dialog and returns what was chosen,
 * or empty if the person closed it without choosing.
 * 
 * A path is typed only when there is no other way. Somebody who knows where
 * their project is knows it as a place they can point at, not as a string they
 * can spell — and a typo in a path is a project that refuses to save with a
 * sentence about a folder that is not there.
 */
export function PickFolder($from: string): $CancellablePromise<string> {
    return $Call.ByID(78060566, $from);
}

/**
 * PollSource reads a source now, so nobody has to wait out an interval to see a
 * change.
 */
export function PollSource(name: string): $CancellablePromise<model$0.InboxGroup[] | null> {
    return $Call.ByID(3976612943, name);
}

/**
 * Projects is the registry of places work happens.
 */
export function Projects(): $CancellablePromise<model$0.Project[] | null> {
    return $Call.ByID(3674097273);
}

/**
 * ReadDoc opens a notes screen's file. The path is relative to the card's
 * working folder — the same folder the agent works in, so a plan it wrote is
 * the file a person edits rather than a copy of it.
 * 
 * A file that is not there yet is empty rather than an error: a stage may well
 * declare notes the agent has not written yet, and an error there would be the
 * ribbon refusing to show a blank page.
 */
export function ReadDoc(cardID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3010567507, cardID, name);
}

/**
 * RemoveFromFlow takes a card off its flow and back into the inbox.
 */
export function RemoveFromFlow(cardID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(361858351, cardID);
}

/**
 * RestartToUpdate closes this application and brings back the newer one.
 * Everything a card was in the middle of is in the database; a running agent is
 * not, and is closed the way quitting closes it.
 */
export function RestartToUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2248632910);
}

/**
 * Ribbon is one card's strip of screens.
 */
export function Ribbon(cardID: string): $CancellablePromise<engine$0.RibbonView> {
    return $Call.ByID(898382539, cardID);
}

/**
 * Ribbons is every card in work: one card in work is one ribbon, and there is
 * no other kind (docs/system.md §12.1).
 */
export function Ribbons(): $CancellablePromise<engine$0.RibbonView[] | null> {
    return $Call.ByID(62943144);
}

/**
 * SaveAgent adds or replaces a registry entry.
 */
export function SaveAgent(a: model$0.Agent): $CancellablePromise<model$0.Agent> {
    return $Call.ByID(1761974331, a);
}

/**
 * SaveFlow validates a flow and stores it. The whole graph is checked before it
 * is taken, and a refusal says which part is wrong.
 */
export function SaveFlow(flow: model$0.Flow): $CancellablePromise<model$0.Flow> {
    return $Call.ByID(2157757914, flow);
}

/**
 * SaveProject adds or edits one entry.
 * 
 * Whether the folder is actually there is asked here rather than in the domain,
 * which touches no disk — and here is also where a person is looking, so a path
 * with a typo in it is refused while they can still see what they typed.
 */
export function SaveProject(p: model$0.Project): $CancellablePromise<model$0.Project> {
    return $Call.ByID(4242958159, p);
}

/**
 * SaveSource adds or replaces a source.
 */
export function SaveSource(src: model$0.Source): $CancellablePromise<model$0.Source> {
    return $Call.ByID(890995235, src);
}

/**
 * SessionEvents is one agent run as it happened: its messages, its thoughts and
 * its tool calls, oldest first. sinceSeq is what the caller already has, so a
 * screen that is following a live session asks only for the rest of it.
 * 
 * It reads the same rows the manager writes as it goes, rather than a second
 * stream alongside them: what the card's history is made of and what the
 * ribbon shows are one record.
 */
export function SessionEvents(sessionID: string, sinceSeq: number): $CancellablePromise<store$0.SessionEvent[] | null> {
    return $Call.ByID(1587394828, sessionID, sinceSeq);
}

/**
 * SetAssignee says who the card is for. An agent's name means "let this agent
 * work it"; anything else means a person took it, and then no agent starts.
 */
export function SetAssignee(cardID: string, who: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(3654695766, cardID, who);
}

/**
 * SetCardProject says where a card's work happens. Beside the assignee on
 * purpose: both are about by whom and where, and both are a person's answer
 * rather than the graph's.
 */
export function SetCardProject(cardID: string, projectID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(1424901168, cardID, projectID);
}

/**
 * SetProp sets a property on a card and tells the engine, because a property is
 * how a person answers a waiting stage. Which stage cares, and whether this was
 * the value it wanted, is the engine's to decide — setting anything else is
 * simply not addressed to it.
 */
export function SetProp(cardID: string, name: string, value: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(3244103020, cardID, name, value);
}

/**
 * SetUpdatesEnabled turns the automatic check on or off. It takes effect on the
 * next tick, not at the next launch.
 */
export function SetUpdatesEnabled(enabled: boolean): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(2468448178, enabled);
}

/**
 * SkipUpdate stops offering the release now on offer. Remembered across
 * restarts, or the button would mean «до перезапуска».
 */
export function SkipUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1510861001);
}

/**
 * Sources is the registry with every source's rules.
 */
export function Sources(): $CancellablePromise<model$0.Source[] | null> {
    return $Call.ByID(3797444719);
}

/**
 * TakeIntoWork puts an inbox card onto a flow. This is the one way a card
 * starts moving, and it is a person's decision.
 */
export function TakeIntoWork(cardID: string, flowID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(1683275391, cardID, flowID);
}

/**
 * UpdateState is everything the «Обновление» screen draws. A build with no
 * updater answers too, and says so: the screen then shows the version and
 * nothing else, rather than an empty panel.
 */
export function UpdateState(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(3371956631);
}

/**
 * Vocabulary returns those sets.
 */
export function Vocabulary(): $CancellablePromise<$models.Vocabulary> {
    return $Call.ByID(3928170955);
}

/**
 * WriteDoc saves a notes screen's file, creating the folders it needs.
 */
export function WriteDoc(cardID: string, name: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(130752024, cardID, name, text);
}
