// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * API is what the UI calls. One service rather than several: the screens do not
 * divide along the same lines the packages do — the card screen needs the flow,
 * the sessions and the open question at once — and a facade that hands back
 * whole screens is less to keep in step than four that hand back fragments.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as acp$0 from "../acp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCard files a card somebody typed straight into the inbox.
 */
export function AddCard(sourceName: string, title: string, body: string): $CancellablePromise<model$0.Card> {
    return $Call.ByID(3801214340, sourceName, title, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddComment writes a person's note into a card's history.
 */
export function AddComment(cardID: string, text: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(2030529371, cardID, text).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddItem files an item into a source by hand. It goes through the source's own
 * file rather than straight into a card, so a hand-added item is an item like
 * any other: it meets the same rules and survives the file being read again.
 */
export function AddItem(sourceName: string, title: string, body: string): $CancellablePromise<model$0.InboxGroup[]> {
    return $Call.ByID(1502436789, sourceName, title, body).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Agents is the registry with the adapter check beside it, because "is this
 * agent usable here" is the question a person opens that screen with.
 */
export function Agents(): $CancellablePromise<$models.AgentsView> {
    return $Call.ByID(4132736297).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Answer delivers a person's answer to an agent's question.
 */
export function Answer(questionID: string, answer: acp$0.Answer): $CancellablePromise<void> {
    return $Call.ByID(4238054837, questionID, answer);
}

/**
 * Attention is every question an agent is waiting on, oldest first.
 */
export function Attention(): $CancellablePromise<acp$0.Attention[]> {
    return $Call.ByID(978520023).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * CancelCard stops whatever is running for a card. A cancelled session produces
 * no outcome: the person who stopped it decides what happens next.
 */
export function CancelCard(cardID: string): $CancellablePromise<void> {
    return $Call.ByID(1480875471, cardID);
}

/**
 * Card is everything about one card.
 */
export function Card(cardID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(1660277701, cardID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteAgent removes an entry, refusing while a flow still names it: a stage
 * whose crew is nobody is a card that silently never starts, and finding that
 * out here is better than finding it out mid-run.
 */
export function DeleteAgent(name: string): $CancellablePromise<void> {
    return $Call.ByID(2879232337, name);
}

/**
 * DeleteFlow removes a flow. Cards standing on it stop advancing by themselves
 * and say so; nothing else happens to them.
 */
export function DeleteFlow(flowID: string): $CancellablePromise<void> {
    return $Call.ByID(2555422584, flowID);
}

/**
 * DeleteSource removes a source. The cards it brought stay: they are work, and
 * the source is only where they came from.
 */
export function DeleteSource(name: string): $CancellablePromise<void> {
    return $Call.ByID(797133365, name);
}

/**
 * Done is the closed cards, newest first.
 */
export function Done(): $CancellablePromise<model$0.Card[]> {
    return $Call.ByID(669172479).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * DropCard files a card away without doing it. The card is kept — what was
 * dropped and why is the sort of thing somebody asks about later.
 */
export function DropCard(cardID: string): $CancellablePromise<void> {
    return $Call.ByID(216846176, cardID);
}

/**
 * EditCard changes a card's own text.
 */
export function EditCard(cardID: string, title: string, body: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(2223589865, cardID, title, body).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FlowCards lists the cards travelling a flow, with the stage each stands on.
 */
export function FlowCards(flowID: string): $CancellablePromise<$models.StageCard[]> {
    return $Call.ByID(3466565678, flowID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * FlowOverview is one flow and where its cards are along it.
 */
export function FlowOverview(flowID: string): $CancellablePromise<engine$0.FlowOverview> {
    return $Call.ByID(283715336, flowID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Flows is every flow, whole.
 */
export function Flows(): $CancellablePromise<model$0.Flow[]> {
    return $Call.ByID(2493457172).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * InWork is every card currently travelling a flow.
 */
export function InWork(): $CancellablePromise<$models.CardSummary[]> {
    return $Call.ByID(2027618605).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * Inbox is everything waiting to be taken into work, grouped by what brought it.
 */
export function Inbox(): $CancellablePromise<model$0.InboxGroup[]> {
    return $Call.ByID(64525769).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * MoveTo puts a card on a stage by hand. A person is always above the graph.
 */
export function MoveTo(cardID: string, stageID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(3200309791, cardID, stageID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PollSource reads a source now, so nobody has to wait out an interval to see a
 * change.
 */
export function PollSource(name: string): $CancellablePromise<model$0.InboxGroup[]> {
    return $Call.ByID(3976612943, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RemoveFromFlow takes a card off its flow and back into the inbox.
 */
export function RemoveFromFlow(cardID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(361858351, cardID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveAgent adds or replaces a registry entry.
 */
export function SaveAgent(a: model$0.Agent): $CancellablePromise<model$0.Agent> {
    return $Call.ByID(1761974331, a).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SaveFlow validates a flow and stores it. The whole graph is checked before it
 * is taken, and a refusal says which part is wrong.
 */
export function SaveFlow(flow: model$0.Flow): $CancellablePromise<model$0.Flow> {
    return $Call.ByID(2157757914, flow).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SaveSource adds or replaces a source.
 */
export function SaveSource(src: model$0.Source): $CancellablePromise<model$0.Source> {
    return $Call.ByID(890995235, src).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * SetAssignee says who the card is for. An agent's name means "let this agent
 * work it"; anything else means a person took it, and then no agent starts.
 */
export function SetAssignee(cardID: string, who: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(3654695766, cardID, who).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetProp sets a property on a card and tells the engine, because a property is
 * how a person answers a waiting stage. Which stage cares, and whether this was
 * the value it wanted, is the engine's to decide — setting anything else is
 * simply not addressed to it.
 */
export function SetProp(cardID: string, name: string, value: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(3244103020, cardID, name, value).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Sources is the registry with every source's rules.
 */
export function Sources(): $CancellablePromise<model$0.Source[]> {
    return $Call.ByID(3797444719).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * TakeIntoWork puts an inbox card onto a flow. This is the one way a card
 * starts moving, and it is a person's decision.
 */
export function TakeIntoWork(cardID: string, flowID: string): $CancellablePromise<$models.CardView> {
    return $Call.ByID(1683275391, cardID, flowID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Vocabulary returns those sets.
 */
export function Vocabulary(): $CancellablePromise<$models.Vocabulary> {
    return $Call.ByID(3928170955).then(($result: any) => {
        return $$createType18($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Card.createFrom;
const $$createType1 = $models.CardView.createFrom;
const $$createType2 = model$0.InboxGroup.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.AgentsView.createFrom;
const $$createType5 = acp$0.Attention.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = $models.StageCard.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = engine$0.FlowOverview.createFrom;
const $$createType11 = model$0.Flow.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.CardSummary.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = model$0.Agent.createFrom;
const $$createType16 = model$0.Source.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.Vocabulary.createFrom;
