// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as acp$0 from "../acp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * AgentsView is the registry and what this machine can actually run.
 */
export interface AgentsView {
    "agents": model$0.Agent[] | null;
    "adapters": acp$0.AdapterStatus[] | null;
}

/**
 * CardSummary is a card in a list: itself, where it is, and whether it wants
 * something from a person.
 */
export interface CardSummary {
    "card": model$0.Card;
    "flow"?: engine$0.CardFlow | null;
    "asking"?: boolean;
}

/**
 * CardView is the whole card screen in one answer.
 */
export interface CardView {
    "card": model$0.Card;
    "flow"?: engine$0.CardFlow | null;
    "journal": model$0.JournalEntry[] | null;
    "sessions": store$0.Session[] | null;
    "events": model$0.FlowEvent[] | null;

    /**
     * Question is what the agent is waiting to hear, if it is waiting.
     */
    "question"?: acp$0.Question | null;
}

/**
 * Language is what the UI needs to pick its words: what the person chose, and
 * the languages the system prefers, best first, for when they chose the system.
 */
export interface Language {
    /**
     * Chosen is a language tag the UI has a dictionary for, or LangSystem.
     */
    "chosen": string;

    /**
     * System is the operating system's preferred languages as BCP 47 tags. It
     * is empty where they cannot be learned from here, and the UI then asks its
     * webview instead.
     */
    "system": string[] | null;
}

/**
 * NotificationWords is what a notification says around the agent's own words,
 * in the person's language. The UI is where that language is known, so the UI
 * hands these over when it starts; until it has, there is nobody to word a
 * notification for, and none is shown — the question waits on its card.
 */
export interface NotificationWords {
    /**
     * Asks is the title of a question on no card.
     */
    "asks": string;

    /**
     * Permission wraps what an agent asks to do: «{what}» is the tool and the
     * agent's own title for the call, whichever it gave.
     */
    "permission": string;

    /**
     * PermissionBare is a permission question with nothing to say what for.
     */
    "permissionBare": string;
    "reply": string;
    "replyPlaceholder": string;
}

/**
 * StageCard is a card as the flow view draws it.
 */
export interface StageCard {
    "card": model$0.Card;
    "stageId": string;
    "asking"?: boolean;
}

/**
 * TerminalHandle is what a terminal screen needs to connect: which terminal,
 * and where its socket is.
 */
export interface TerminalHandle {
    "id": string;
    "url": string;
}

/**
 * UpdateState is what the «Update» screen draws.
 */
export interface UpdateState {
    /**
     * Supported is false where there is nothing to update: a headless run, a
     * test, a build with no updater wired in.
     */
    "supported": boolean;
    "enabled": boolean;
    "currentVersion": string;

    /**
     * Status is the framework's own state — one of unconfigured, idle,
     * checking, up-to-date, available, downloading, verifying, installing,
     * ready, error — read off the Updater rather than inferred from which
     * event arrived: the bus dispatches each event in a goroutine of its own,
     * so two can be seen out of order, and a status that went backwards would
     * be a progress bar that did.
     */
    "status": string;
    "availableVersion"?: string;
    "releaseName"?: string;
    "notes"?: string;
    "sizeBytes"?: number;
    "downloaded"?: number;
    "skippedVersion"?: string;
    "lastCheckedAt"?: string;

    /**
     * Error is what went wrong, verbatim and in the framework's English:
     * "dial tcp: lookup updates.deffun.org: no such host". ErrorStage is the
     * step it went wrong at — check, download, verify, install — and it is
     * there because the screen says the actionable half itself, in the
     * person's language.
     * The verbatim text stays underneath it, in small print: it is what a bug
     * report needs and nothing on this side can supply it.
     */
    "error"?: string;
    "errorStage"?: string;

    /**
     * Path is where the settings file lives, so the screen can name it when
     * something has to be looked at by hand.
     */
    "path"?: string;
}

/**
 * Vocabulary is the closed sets the editor offers. Sent from here so the UI can
 * never offer a trigger or an action the engine does not implement. Only the
 * members are sent: what each is called is the UI's to say.
 */
export interface Vocabulary {
    "triggers": model$0.Trigger[] | null;
    "actions": string[] | null;

    /**
     * Where an agent stage runs — the terminal somebody sits at, or a session
     * nobody watches (docs/system.md §4.1.1).
     */
    "works": string[] | null;
    "kinds": string[] | null;
    "ruleActions": string[] | null;

    /**
     * The card's own field for how a stage ended, and the two values it takes.
     * Sent so the editor can keep it out of what a stage declares — the engine
     * writes it for every stage — while still offering it to a condition, which
     * is the whole point of it being a closed set.
     */
    "outcomeProperty": string;
    "outcomeValues": string[] | null;

    /**
     * What kinds of screen a stage may declare — the same closed set the
     * ribbon knows how to render, so the editor cannot offer a window nothing
     * can open (docs/system.md §12.2).
     */
    "screenKinds": string[] | null;

    /**
     * What kinds of place work can happen in. One for now — a folder — and the
     * room for the rest is the same room the triggers keep for git.
     */
    "projectKinds": string[] | null;

    /**
     * WorkModes are how a card may work in a repository (model/workmode.go).
     */
    "workModes": string[] | null;

    /**
     * Providers are the hostings a project's remote can be (docs/system.md §15).
     */
    "providers": string[] | null;
}
